weights: ''''''
cfg: ./models/custom_yolov5x.yaml
data: .\data\data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 2
img_size:
- 128
- 128
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov5x_results
exist_ok: false
total_batch_size: 2
world_size: 1
global_rank: -1
save_dir: runs\train\yolov5x_results13
